### PR TITLE
adds right position

### PR DESCRIPTION
**Pull request by lory87**
**This pull request fixes the following issues**:

- adds right position to center lightbox if description is to long

### CODE REVIEW

**Comment by FinalAngel** [comment]
you also have to adapt: https://github.com/divio/classjs-plugins/blob/master/index.html#L19

**Comment by FinalAngel** [comment]
LGTM

**Comment by vxsx** [comment]
please don't remove src/cl.uniform/cl.uniform.min.js

**Comment by lory87** [comment]
@vxsx didn't remove the file src/cl.uniform/cl.uniform.min.js
Maybe there were some compile updates after run grunt

**Comment by vxsx** [comment]
@lory87 it seems that the comment was removed, my bad

**Pull request merged**
